// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTfNuEm5YRa19mpOhNjeIuXqrrgHyGeE',
    appId: '1:275916286082:web:a4d085c82c3c633d1f2c9b',
    messagingSenderId: '275916286082',
    projectId: 'alphabet-learning-daff7',
    authDomain: 'alphabet-learning-daff7.firebaseapp.com',
    storageBucket: 'alphabet-learning-daff7.appspot.com',
    measurementId: 'G-TQXT425RN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc5ijeWewBv9kzi8vnZcAdQDKF_Uxq2QQ',
    appId: '1:275916286082:android:2086d0714b01c2c41f2c9b',
    messagingSenderId: '275916286082',
    projectId: 'alphabet-learning-daff7',
    storageBucket: 'alphabet-learning-daff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUpGP7upPoZxftZBnpUtfmmgByDQIQECo',
    appId: '1:275916286082:ios:67427273af63d5b31f2c9b',
    messagingSenderId: '275916286082',
    projectId: 'alphabet-learning-daff7',
    storageBucket: 'alphabet-learning-daff7.appspot.com',
    iosClientId: '275916286082-hh38ed1atss3uu698fdvcsvnse8m8q0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphabetlearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUpGP7upPoZxftZBnpUtfmmgByDQIQECo',
    appId: '1:275916286082:ios:67427273af63d5b31f2c9b',
    messagingSenderId: '275916286082',
    projectId: 'alphabet-learning-daff7',
    storageBucket: 'alphabet-learning-daff7.appspot.com',
    iosClientId: '275916286082-hh38ed1atss3uu698fdvcsvnse8m8q0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphabetlearning',
  );
}
